name: E2E tests for Widgets

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

env:
  DEVELOPER_DIR: /Applications/Xcode_11.4.app/Contents/Developer

jobs:
  build-and-push-image-job:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Environment Variables
      run: |
        echo "BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
        echo "BUILD_VER=1.0.${{ github.run_number }}" >> $GITHUB_ENV
        echo "GIT_REF=$((git symbolic-ref -q --short HEAD || git describe --tags --exact-match) | awk 'gsub(/\//, \'-\')')" >> $GITHUB_ENV
        echo "GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
        echo "IMAGE=ghcr.io/${{ github.repository_owner }}/headless-browsers-node-14" >> $GITHUB_ENV

    # The rest steps of this job will only be run if cache misses.
    # Login to GHCR, Build and Push steps of the job are performed only on changes
    # to the Dockerfile.
    - name: Cache Build Image
      id: cache-build-image
      uses: actions/cache@v2
      with:
        path: ~/.docker/machine/cache/boot2docker.iso 
        key: ${{ runner.os }}-${{ hashFiles('Dockerfile') }}

    - name: Install docker # Taken from https://github.com/actions/virtual-environments/issues/1143#issuecomment-652264388
      run: |
        mkdir -p ~/.docker/machine/cache
        curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
        brew install docker docker-machine
        docker-machine create --driver virtualbox default
        docker-machine env default
      if: steps.cache-build-image.outputs.cache-hit != 'true'

    - name: Login to DockerHub
      uses: docker/login-action@v1.9.0
      if: steps.cache-build-image.outputs.cache-hit != 'true'
      with:
        # Login credentials are provided by Github Actions CI
        # Reference:
        # - github context (https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context)
        # - workflow recommendations (https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions)
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    - name: Build and push
      id: docker-build-push
      uses: docker/build-push-action@v2
      if: steps.cache-build-image.outputs.cache-hit != 'true'
      with:
        push: true
        labels: |
          org.opencontainers.image.authors=${{ github.repository_owner }}
          org.opencontainers.image.created=${{ env.BUILD_DATE }}
          org.opencontainers.image.description=Created from commit ${{ env.GIT_SHA }} and ref ${{ env.GIT_REF }}
          org.opencontainers.image.ref.name=${{ env.GIT_REF }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.version=${{ env.BUILD_VER }}
        tags: |
          ${{ env.IMAGE }}:latest
          ${{ env.IMAGE }}:${{ env.GIT_SHA }}
          ${{ env.IMAGE }}:${{ env.GIT_REF }}
          ${{ env.IMAGE }}:${{ env.BUILD_VER }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

  test-job:
    runs-on: macos-10.15
    strategy:
      fail-fast: false
      matrix:
        # These are the supported browsers that have a run scripts for CI in `package.json`.
        # Available scripts are `test:e2e:ci-firefox`, `test:e2e:ci-chrome`.
        # They follow the format `test:e2e:ci-<browser>`.
        # These scripts will be run in parallel.
        browser:
            - chromium
            - firefox 

    steps:
    - uses: actions/checkout@v1
    - name: Install docker # Taken from https://github.com/actions/virtual-environments/issues/1143#issuecomment-652264388
      run: |
        mkdir -p ~/.docker/machine/cache
        curl -Lo ~/.docker/machine/cache/boot2docker.iso https://github.com/boot2docker/boot2docker/releases/download/v19.03.12/boot2docker.iso
        brew install docker docker-machine
        docker-machine create --driver virtualbox default
        docker-machine env default
    - name: Login to DockerHub
      uses: docker/login-action@v1.9.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}
    - name: Run tests in ${{ matrix.browser }}
      run: |
        docker run -t -v $PWD:/usr/src/app ghcr.io/${{ github.repository_owner }}/headless-browsers-node-14 sh -c "yarn && npm run test:e2e:ci-${{ matrix.browser }}"
   
    needs: build-and-push-image-job
