name: E2E tests for Widgets

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    working-directory: .

jobs:
  build-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Cache Build Image
      id: cache-build-image
      uses: actions/cache@v2
      with:
        path: |
          Dockerfile
          package.json
        key: ${{ runner.os }}-${{ hashFiles('**/{Dockerfile|package.json}') }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      if: steps.cache-build-image.outputs.cache-hit != 'true'

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.ghcr_token }}

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: headless-browsers-node-14:latest

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}