name: E2E tests for Widgets

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    working-directory: .

jobs:
  build-and-push-image-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Environment Variables
      run: |
        echo "BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
        echo "GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
        echo "BUILD_VER=1.0.${{ github.run_number }}" >> $GITHUB_ENV
        echo "IMAGE=ghcr.io/${{ github.repository_owner }}/headless-browsers-node-14" >> $GITHUB_ENV

    - name: Cache Build Image
      id: cache-build-image
      uses: actions/cache@v2
      with:
        path: |
          Dockerfile
          package.json
        key: ${{ runner.os }}-${{ hashFiles('Dockerfile', 'package.json') }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      if: steps.cache-build-image.outputs.cache-hit != 'true'

    - name: Login to DockerHub
      uses: docker/login-action@v1.9.0
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.ghcr_token }}

    - name: Build and push
      id: docker-build-push
      uses: docker/build-push-action@v2
      with:
        push: true
        labels: |
          org.opencontainers.image.authors=${{ github.repository_owner }}
          org.opencontainers.image.created=${{ env.BUILD_DATE }}
          org.opencontainers.image.description=Created from commit ${{ env.GIT_SHA }} and ref ${{ github.ref }}
          org.opencontainers.image.ref.name=${{ github.ref }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.version=${{ env.BUILD_VER }}
        tags: |
          ${{ env.IMAGE }}:latest
          ${{ env.IMAGE }}:${{ env.GIT_SHA }}
          ${{ env.IMAGE }}:${{ github.ref }}
          ${{ env.IMAGE }}:${{ env.BUILD_VER }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}