name: E2E tests for Widgets

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

defaults:
  run:
    working-directory: /home/runner/work/e2e-ci-tests/e2e-ci-tests


jobs:
  build-and-push-image-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Environment Variables
      run: |
        echo "BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
        echo "BUILD_VER=1.0.${{ github.run_number }}" >> $GITHUB_ENV
        echo "GIT_REF=$(git symbolic-ref -q --short HEAD || git describe --tags --exact-match)" >> $GITHUB_ENV
        echo "GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
        echo "IMAGE=ghcr.io/${{ github.repository_owner }}/headless-browsers-node-14" >> $GITHUB_ENV

    - name: Cache Build Image
      id: cache-build-image
      uses: actions/cache@v2
      with:
        path: Dockerfile
        key: ${{ runner.os }}-${{ hashFiles('Dockerfile') }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      if: steps.cache-build-image.outputs.cache-hit != 'true'

    - name: Login to DockerHub
      uses: docker/login-action@v1.9.0
      if: steps.cache-build-image.outputs.cache-hit != 'true'
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    - name: Build and push
      id: docker-build-push
      uses: docker/build-push-action@v2
      if: steps.cache-build-image.outputs.cache-hit != 'true'
      with:
        push: true
        labels: |
          org.opencontainers.image.authors=${{ github.repository_owner }}
          org.opencontainers.image.created=${{ env.BUILD_DATE }}
          org.opencontainers.image.description=Created from commit ${{ env.GIT_SHA }} and ref ${{ env.GIT_REF }}
          org.opencontainers.image.ref.name=${{ env.GIT_REF }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.version=${{ env.BUILD_VER }}
        tags: |
          ${{ env.IMAGE }}:latest
          ${{ env.IMAGE }}:${{ env.GIT_SHA }}
          ${{ env.IMAGE }}:${{ env.GIT_REF }}
          ${{ env.IMAGE }}:${{ env.BUILD_VER }}

    - name: Image digest
      run: echo ${{ steps.docker_build.outputs.digest }}

  test-job:
    runs-on: ubuntu-latest

    container:
      image: ghcr.io/${{ github.repository_owner }}/headless-browsers-node-14
      credentials:
        username: ${{ github.repository_owner }}
        password: ${{ github.token }}

    steps:
    - uses: actions/checkout@v1

    - name: Get yarn cache directory path
      id: yarn-cache-dir-path
      run: echo "::set-output name=dir::$(yarn cache dir)"

    - name: Cache node modules
      id: cache-node-modules
      uses: actions/cache@v2
      with:
        path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
        key: ${{ runner.os }}-${{ hashFiles('package.json') }}
   
    - run: yarn
      if: steps.cache-node-modules.cache-hit != 'true'
   
    - run: npm run test:e2e:ci
   
    needs: build-and-push-image-job
