name: E2E tests for First Widget

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build-and-push-image-job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set Environment Variables
      run: |
        echo "BUILD_DATE=$(date +'%Y-%m-%d %H:%M:%S')" >> $GITHUB_ENV
        echo "BUILD_VER=1.0.${{ github.run_number }}" >> $GITHUB_ENV
        echo "GIT_REF=$(echo ${{ github.ref }} | awk 'gsub(/refs\/heads\/|refs\/tags\//, "")1' | awk 'gsub(/\//, "-")1')"  >> $GITHUB_ENV
        echo "GIT_SHA=$(echo ${{ github.sha }} | cut -c1-7)" >> $GITHUB_ENV
        echo "IMAGE=us-docker.pkg.dev/troupon-1103/hello/e2e-test" >> $GITHUB_ENV

    - name: Login to Google Artifact Repository
      uses: docker/login-action@v1.9.0
      if: steps.cache-build-image.outputs.cache-hit != 'true'
      with:
        # Login credentials are provided by Github Actions CI
        # Reference:
        # - github context (https://docs.github.com/en/actions/reference/context-and-expression-syntax-for-github-actions#github-context)
        # - workflow recommendations (https://docs.github.com/en/packages/managing-github-packages-using-github-actions-workflows/publishing-and-installing-a-package-with-github-actions)
        registry: us-docker.pkg.dev/troupon-1103/hello
        username: _json_key
        password: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY_JSON }}

    - name: Get Image manifest
      id: get-manifest
      run: |
        set +eo pipefail
        found_manifest=`docker manifest inspect ${{ env.IMAGE }} 2> /dev/null`
        if [ $found_manifest -eq 0 ]; then
          echo "::set-output found=true"
        else
          echo "::set-output found=false"
        fi
      shell: bash

    # The rest steps of this job will only be run if cache misses.
    # Login to GHCR, Build and Push steps of the job are performed only on changes
    # to the Dockerfile.
    - name: Cache Build Image
      id: cache-build-image
      uses: actions/cache@v2
      with:
        path: Dockerfile
        key: ${{ runner.os }}-${{ hashFiles('Dockerfile') }}

    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      if: ${{ steps.cache-build-image.outputs.cache-hit != 'true' || steps.get-manifest.outputs.found != 'true' }}

    - name: Build and push
      id: docker-build-push
      uses: docker/build-push-action@v2
      if: ${{ steps.cache-build-image.outputs.cache-hit != 'true' || steps.get-manifest.outputs.found != 'true' }}
      with:
        push: true
        labels: |
          org.opencontainers.image.authors=${{ github.repository_owner }}
          org.opencontainers.image.created=${{ env.BUILD_DATE }}
          org.opencontainers.image.description=Created from commit ${{ env.GIT_SHA }} and ref ${{ env.GIT_REF }}
          org.opencontainers.image.ref.name=${{ env.GIT_REF }}
          org.opencontainers.image.revision=${{ github.sha }}
          org.opencontainers.image.source=https://github.com/${{ github.repository }}
          org.opencontainers.image.version=${{ env.BUILD_VER }}
        tags: |
          ${{ env.IMAGE }}:latest
          ${{ env.IMAGE }}:${{ env.GIT_SHA }}
          ${{ env.IMAGE }}:${{ env.GIT_REF }}
          ${{ env.IMAGE }}:${{ env.BUILD_VER }}

    - name: Image digest
      run: echo steps.docker_build.outputs.digest

  test-job:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # These are the supported browsers that have a run scripts for CI in `package.json`.
        # Available scripts are `test:e2e:ci-firefox`, `test:e2e:ci-chrome`.
        # They follow the format `test:e2e:ci-<browser>`.
        # These scripts will be run in parallel.
        browser:
            - chromium
            - firefox
    container: 
      image: us-docker.pkg.dev/troupon-1103/hello/e2e-test
      credentials:
        username: _json_key
        password: ${{ secrets.GCLOUD_SERVICE_ACCOUNT_KEY_JSON }}

    steps:
    - uses: actions/checkout@v1

        
    - name: Get npm cache directory
      id: npm-cache-dir
      run: |
        echo "::set-output name=dir::$(npm config get cache)"

    - uses: actions/cache@v2
      with:
        path: ${{ steps.npm-cache-dir.outputs.dir }}
        key: ${{ runner.os }}-node-${{ hashFiles('package.json') }}
        restore-keys: |
          ${{ runner.os }}-node-
   
    # Run yarn only when no cache found.
    - run: npm install
   
    - name: Run first-offers tests in ${{ matrix.browser }} browser
      run: |
        mkdir -p /github/home/.firefox/_logs
        chmod a+rX /github/home
        chown -R root:root /github/home
        chmod 0755 /github/home
        chmod -R 0755 /github/home
        npm run test:e2e:ci-${{ matrix.browser }} -- src/widgets/first-offers/*.e2e.ts

    needs: build-and-push-image-job
